use std::path::{Path, PathBuf};

// =============================================================================
// Template
// =============================================================================

/// Lua DSL cam script template. Placeholders use `__CAM_*__` sentinel form to
/// avoid collisions with `${...}` style Lua string formatting patterns.
///
/// Placeholders:
/// - `__CAM_OUT__`          — absolute path of the output file (header comment)
/// - `__CAM_PERSONA_ID__`   — persona id slug
/// - `__CAM_TOPIC__`        — topic slug
/// - `__CAM_SCENE__`        — scene description (Lua-escaped, header comment)
/// - `__CAM_BASE_SNIPPET__` — persona base snippet (resolved from cam-vdsl bases)
/// - `__CAM_SHOTS_TABLE__`  — Lua table literal for shots array
const CAM_LUA_TEMPLATE: &str = r#"--- __CAM_OUT__ — __CAM_PERSONA_ID__ cam (__CAM_TOPIC__)
-- Generated by vdsl_cam_lua_init.
-- Scene: __CAM_SCENE__
local vdsl = require("vdsl")

-- Overlay user catalogs (project-personal vocabulary).
-- Directory is git-untracked, any literal stays in user-personal space.
-- No-op if the directory or specific catalog files don't exist.
local home = os.getenv("HOME")
if home and home ~= "" then
  vdsl.use_catalogs(home .. "/.claude/skills/cam-vdsl/catalogs")
end

local C = vdsl.catalogs

local w = vdsl.world {
  model     = "waiIllustrious_v16.safetensors",
  clip_skip = 2,
}

local neg = C.quality.neg_default
          + C.quality.neg_anatomy
          + C.quality.neg_face
          + C.figure.expression.bad_face

__CAM_BASE_SNIPPET__

local common_cam = C.camera.medium_shot
                 + C.camera.eye_level
                 + C.camera.portrait_lens
                 + C.camera.shallow_dof

local shots = __CAM_SHOTS_TABLE__

for _, s in ipairs(shots) do
  local result = vdsl.render {
    world   = w,
    cast    = { vdsl.cast { subject = base:with((s.trait or vdsl.trait("")) + common_cam), negative = neg } },
    sampler = "euler_ancestral",
    steps   = 25,
    cfg     = 6.0,
    seed    = s.seed,
    size    = { 832, 1216 },
  }
  vdsl.emit(s.name, result)
end
"#;

// =============================================================================
// Public types
// =============================================================================

/// Specification for a single shot in a cam sequence.
#[derive(Debug, Clone)]
pub struct CamShotSpec {
    /// Shot name (filename-safe: `[a-zA-Z0-9_-]` only).
    pub name: String,
    /// RNG seed for this shot.
    pub seed: i64,
    /// Trait DSL expression string appended to base subject. May be empty.
    pub trait_dsl: String,
}

/// Result returned by a successful [`scaffold_cam_lua`] call.
#[derive(Debug, serde::Serialize)]
pub struct CamLuaScaffoldResult {
    /// Absolute path of the created (or overwritten) Lua script.
    pub script_file: PathBuf,
    /// `true` if the file was newly created; `false` if it was overwritten
    /// (only possible when `overwrite=true`).
    pub file_created: bool,
    /// Describes which base-resolution path was taken.
    /// - `"file:<path>"` — base snippet read from a file
    /// - `"fallback:default"` — thin default base was used
    pub base_source: String,
}

/// Errors that can occur when scaffolding a new cam Lua script.
#[derive(Debug, thiserror::Error)]
pub enum CamLuaScaffoldError {
    /// The persona_id is invalid (empty or contains characters outside `[a-zA-Z0-9_-]`).
    #[error("invalid persona_id: {0}")]
    InvalidPersonaId(String),

    /// The topic is invalid (empty or contains characters outside `[a-zA-Z0-9_-]`).
    #[error("invalid topic: {0}")]
    InvalidTopic(String),

    /// A shot name is invalid (must be filename-safe: `[a-zA-Z0-9_-]` only).
    #[error("invalid shot name: {0}")]
    InvalidShotName(String),

    /// A cam Lua file already exists at the target path and `overwrite` was not requested.
    #[error("cam script '{0}' already exists (pass overwrite=true to force)")]
    AlreadyExists(String),

    /// An I/O error occurred while creating directories or writing the file.
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// The home directory could not be resolved (needed for base snippet path resolution).
    #[error("home directory not found")]
    NoHomeDir,
}

// =============================================================================
// Internal helpers
// =============================================================================

/// Returns today's date in compact `YYMMDD` format (local time).
fn today_compact() -> String {
    chrono::Local::now().format("%y%m%d").to_string()
}

/// Returns today's date in `YYYYMM` format (local time), used for default shot naming.
fn today_yyyymm() -> String {
    chrono::Local::now().format("%Y%m").to_string()
}

/// Validates that `s` is a non-empty slug consisting only of `[a-zA-Z0-9_-]`.
fn validate_slug(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Escapes `s` for use inside a Lua double-quoted string literal.
/// Replaces `\` → `\\` and `"` → `\"`.
/// Newlines are not allowed (callers must validate before calling).
fn lua_str_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Resolves the base snippet for `persona_id` using the 3-stage fallback defined
/// in cam-vdsl SKILL §"Persona 別 base subject の解決":
///
/// 1. `~/.claude/skills/cam-vdsl/bases/<persona_id>.lua`
/// 2. `~/.claude/skills/snap-<persona_id>/<persona_id>_base.lua` (legacy)
/// 3. Thin default base literal
///
/// Returns `(snippet, source_label)` where `source_label` is either
/// `"file:<path>"` or `"fallback:default"`.
///
/// IO errors that are `NotFound` or `PermissionDenied` are silently absorbed
/// and trigger fallback. Other IO errors propagate as `CamLuaScaffoldError::Io`.
fn resolve_base_snippet(persona_id: &str) -> Result<(String, String), CamLuaScaffoldError> {
    let home = dirs::home_dir().ok_or(CamLuaScaffoldError::NoHomeDir)?;

    // Stage 1: ~/.claude/skills/cam-vdsl/bases/<persona_id>.lua
    let stage1_path = home
        .join(".claude")
        .join("skills")
        .join("cam-vdsl")
        .join("bases")
        .join(format!("{persona_id}.lua"));
    match std::fs::read_to_string(&stage1_path) {
        Ok(snippet) => {
            let source = format!("file:{}", stage1_path.display());
            return Ok((snippet, source));
        }
        Err(e)
            if e.kind() == std::io::ErrorKind::NotFound
                || e.kind() == std::io::ErrorKind::PermissionDenied => {}
        Err(e) => return Err(CamLuaScaffoldError::Io(e)),
    }

    // Stage 2: ~/.claude/skills/snap-<persona_id>/<persona_id>_base.lua (legacy)
    let stage2_path = home
        .join(".claude")
        .join("skills")
        .join(format!("snap-{persona_id}"))
        .join(format!("{persona_id}_base.lua"));
    match std::fs::read_to_string(&stage2_path) {
        Ok(snippet) => {
            let source = format!("file:{}", stage2_path.display());
            // The legacy base file uses `local <persona_id>_base = ...` as the identifier.
            // The template expects `base`, so we append an alias line.
            let alias_id = format!("{persona_id}_base");
            let snippet = if snippet.contains(&format!("local {alias_id}")) {
                format!("{snippet}\nlocal base = {alias_id}")
            } else {
                snippet
            };
            return Ok((snippet, source));
        }
        Err(e)
            if e.kind() == std::io::ErrorKind::NotFound
                || e.kind() == std::io::ErrorKind::PermissionDenied => {}
        Err(e) => return Err(CamLuaScaffoldError::Io(e)),
    }

    // Stage 3: thin default base
    let default_snippet = r#"local base = vdsl.subject("1girl, solo, 20 years old")
  :with(C.figure.expression.smile)
  :quality("high")
  :style("photo")"#
        .to_string();
    Ok((default_snippet, "fallback:default".to_string()))
}

/// Builds a Lua table literal for the shots array.
///
/// Each shot produces a table entry:
/// ```lua
/// { name = "...", seed = N, trait = <trait_dsl literal> }
/// ```
/// `trait_dsl` is emitted **verbatim** as a Lua expression so callers can
/// pass catalog references (`"C.figure.hair.long"`), composed expressions
/// (`"C.figure.clothing.t_shirt + C.figure.expression.smile"`), or raw-text
/// wrappers (`"vdsl.trait(\"red dress, smiling\")"`). When `trait_dsl` is
/// empty the `trait` field is set to `nil`.
fn build_shots_table(shots: &[CamShotSpec]) -> String {
    let mut entries: Vec<String> = Vec::new();
    for s in shots {
        let name_escaped = lua_str_escape(&s.name);
        let trait_val = if s.trait_dsl.is_empty() {
            "nil".to_string()
        } else {
            // Pass-through: trait_dsl is a Lua expression, not a raw string.
            // Callers wanting raw text use `vdsl.trait("...")` explicitly.
            s.trait_dsl.clone()
        };
        entries.push(format!(
            "  {{ name = \"{name_escaped}\", seed = {seed}, trait = {trait_val} }}",
            seed = s.seed,
        ));
    }
    format!("{{\n{}\n}}", entries.join(",\n"))
}

// =============================================================================
// Public API
// =============================================================================

/// Scaffold a new cam Lua DSL script at `<root>/<persona_id>_cam_<topic>.lua`.
///
/// The generated file uses `vdsl.render` loops following the cam-vdsl SKILL
/// §手順 7 structure. The persona base subject snippet is resolved from
/// `~/.claude/skills/cam-vdsl/bases/<persona_id>.lua` (3-stage fallback).
///
/// # Arguments
///
/// * `persona_id` — persona slug (must match `^[a-zA-Z0-9_-]+$`)
/// * `scene` — scene description embedded in header comment (no newlines)
/// * `shots` — shot specifications; when `None` a single default shot is generated
/// * `topic` — topic slug; when `None` defaults to `snap_YYMMDD`
/// * `root` — projects root directory (caller typically passes result of `resolve_projects_root`)
/// * `overwrite` — when `false` return an error if target already exists
///
/// # Returns
///
/// A [`CamLuaScaffoldResult`] with the absolute path of the created/overwritten
/// script, whether it was newly created, and which base-resolution path was taken.
///
/// # Errors
///
/// - [`CamLuaScaffoldError::InvalidPersonaId`] — persona_id fails slug validation
/// - [`CamLuaScaffoldError::InvalidTopic`] — topic fails slug validation
/// - [`CamLuaScaffoldError::InvalidShotName`] — a shot name fails slug validation
/// - [`CamLuaScaffoldError::AlreadyExists`] — target exists and `overwrite` is `false`
/// - [`CamLuaScaffoldError::Io`] — directory creation or file write fails
/// - [`CamLuaScaffoldError::NoHomeDir`] — home directory could not be resolved
pub fn scaffold_cam_lua(
    persona_id: &str,
    scene: &str,
    shots: Option<&[CamShotSpec]>,
    topic: Option<&str>,
    root: &Path,
    overwrite: bool,
) -> Result<CamLuaScaffoldResult, CamLuaScaffoldError> {
    // Validate persona_id
    if !validate_slug(persona_id) {
        return Err(CamLuaScaffoldError::InvalidPersonaId(format!(
            "'{persona_id}' must be non-empty and match [a-zA-Z0-9_-]"
        )));
    }

    // Resolve topic
    let resolved_topic = match topic {
        Some(t) => {
            if !validate_slug(t) {
                return Err(CamLuaScaffoldError::InvalidTopic(format!(
                    "'{t}' must be non-empty and match [a-zA-Z0-9_-]"
                )));
            }
            t.to_string()
        }
        None => format!("snap_{}", today_compact()),
    };

    // Validate scene (no newlines allowed — would break Lua line comment)
    if scene.contains('\n') || scene.contains('\r') {
        return Err(CamLuaScaffoldError::InvalidTopic(
            "scene must not contain newlines".to_string(),
        ));
    }

    // Resolve shots (build or use single-shot fallback)
    let default_shot;
    let shots_slice: &[CamShotSpec] = match shots {
        Some(s) => {
            // Validate all shot names
            for shot in s.iter() {
                if !validate_slug(&shot.name) {
                    return Err(CamLuaScaffoldError::InvalidShotName(format!(
                        "shot name '{}' must be non-empty and match [a-zA-Z0-9_-]",
                        shot.name
                    )));
                }
                // Also reject newlines in trait_dsl
                if shot.trait_dsl.contains('\n') || shot.trait_dsl.contains('\r') {
                    return Err(CamLuaScaffoldError::InvalidShotName(format!(
                        "shot '{}' trait_dsl must not contain newlines",
                        shot.name
                    )));
                }
            }
            s
        }
        None => {
            let yyyymm = today_yyyymm();
            default_shot = [CamShotSpec {
                name: format!("{persona_id}-{yyyymm}-V1-{resolved_topic}"),
                seed: 1234,
                trait_dsl: String::new(),
            }];
            &default_shot
        }
    };

    // Determine target path
    let target_path = root.join(format!("{persona_id}_cam_{resolved_topic}.lua"));

    let was_existing = target_path.exists();
    if was_existing && !overwrite {
        return Err(CamLuaScaffoldError::AlreadyExists(
            target_path.display().to_string(),
        ));
    }

    // Resolve base snippet (crux: persona_id-driven, never fixed skeleton)
    let (base_snippet, base_source) = resolve_base_snippet(persona_id)?;

    // auto-mkdir (crux: server-side Write + auto-mkdir)
    std::fs::create_dir_all(root)?;

    // Build shots table Lua literal
    let shots_table = build_shots_table(shots_slice);

    // Expand template
    let out_path_str = target_path.display().to_string();
    let scene_escaped = lua_str_escape(scene);
    let content = CAM_LUA_TEMPLATE
        .replace("__CAM_OUT__", &out_path_str)
        .replace("__CAM_PERSONA_ID__", persona_id)
        .replace("__CAM_TOPIC__", &resolved_topic)
        .replace("__CAM_SCENE__", &scene_escaped)
        .replace("__CAM_BASE_SNIPPET__", &base_snippet)
        .replace("__CAM_SHOTS_TABLE__", &shots_table);

    std::fs::write(&target_path, &content)?;

    Ok(CamLuaScaffoldResult {
        script_file: target_path,
        file_created: !was_existing,
        base_source,
    })
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn setup() -> TempDir {
        tempfile::tempdir().expect("tempdir")
    }

    // -------------------------------------------------------------------------
    // T1: happy path — all args specified, file created with expected content
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_happy_path() {
        let td = setup();
        let root = td.path().to_path_buf();

        let shots = vec![CamShotSpec {
            name: "persona_a-202505-V1-office".to_string(),
            seed: 42,
            trait_dsl: "business_suit".to_string(),
        }];
        let result = scaffold_cam_lua(
            "persona_a",
            "Indoor office scene",
            Some(&shots),
            Some("office"),
            &root,
            false,
        )
        .expect("scaffold");

        assert!(result.file_created);
        let content = std::fs::read_to_string(&result.script_file).expect("read");

        // persona_id and topic in file path
        assert!(result.script_file.ends_with("persona_a_cam_office.lua"));
        // content contains persona_id and topic
        assert!(content.contains("persona_a"));
        assert!(content.contains("office"));
        // scene embedded
        assert!(content.contains("Indoor office scene"));
        // shot name embedded
        assert!(content.contains("persona_a-202505-V1-office"));
        // seed embedded
        assert!(content.contains("42"));
        // trait embedded
        assert!(content.contains("business_suit"));
        // base snippet present (default fallback since bases dir won't exist in test env)
        assert!(content.contains("local base"));
        // no unfilled placeholders
        assert!(!content.contains("__CAM_"));
    }

    // -------------------------------------------------------------------------
    // T2: shots=None produces single-shot fallback
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_shots_none_fallback() {
        let td = setup();
        let root = td.path().to_path_buf();

        let result = scaffold_cam_lua("persona_a", "park scene", None, Some("park"), &root, false)
            .expect("scaffold");

        let content = std::fs::read_to_string(&result.script_file).expect("read");
        // Single shot fallback name: <persona>-YYYYMM-V1-<topic>
        assert!(content.contains("persona_a-"));
        assert!(content.contains("-V1-park"));
        // seed = 1234
        assert!(content.contains("1234"));
    }

    // -------------------------------------------------------------------------
    // T3: topic=None produces snap_YYMMDD fallback
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_topic_none_fallback() {
        let td = setup();
        let root = td.path().to_path_buf();

        let result =
            scaffold_cam_lua("persona_a", "default scene", None, None, &root, false).expect("scaffold");

        let file_name = result
            .script_file
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_string();
        // filename should be persona_a_cam_snap_YYMMDD.lua
        assert!(file_name.starts_with("persona_a_cam_snap_"));
        assert!(file_name.ends_with(".lua"));
    }

    // -------------------------------------------------------------------------
    // T4: overwrite=false fails on second call
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_overwrite_false_fails() {
        let td = setup();
        let root = td.path().to_path_buf();

        scaffold_cam_lua("persona_a", "scene", None, Some("test"), &root, false).expect("first");

        let err = scaffold_cam_lua("persona_a", "scene", None, Some("test"), &root, false)
            .expect_err("second should fail");

        assert!(
            matches!(err, CamLuaScaffoldError::AlreadyExists(_)),
            "expected AlreadyExists, got {err:?}"
        );
    }

    // -------------------------------------------------------------------------
    // T5: overwrite=true succeeds on second call, file_created=false
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_overwrite_true_succeeds() {
        let td = setup();
        let root = td.path().to_path_buf();

        scaffold_cam_lua("persona_a", "scene", None, Some("test"), &root, false).expect("first");
        let result =
            scaffold_cam_lua("persona_a", "scene", None, Some("test"), &root, true).expect("overwrite");

        assert!(
            !result.file_created,
            "overwrite should yield file_created=false"
        );
    }

    // -------------------------------------------------------------------------
    // T6: invalid persona_id returns InvalidPersonaId
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_invalid_persona_id() {
        let td = setup();
        let root = td.path().to_path_buf();

        let err = scaffold_cam_lua("", "scene", None, Some("t"), &root, false).expect_err("empty");
        assert!(matches!(err, CamLuaScaffoldError::InvalidPersonaId(_)));

        let err =
            scaffold_cam_lua("foo/bar", "scene", None, Some("t"), &root, false).expect_err("slash");
        assert!(matches!(err, CamLuaScaffoldError::InvalidPersonaId(_)));
    }

    // -------------------------------------------------------------------------
    // T7: base snippet not found → fallback default is used
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_base_fallback_default() {
        let td = setup();
        let root = td.path().to_path_buf();

        // Use a persona_id unlikely to have a real bases file in CI
        let result = scaffold_cam_lua(
            "nonexistent_persona_xyz",
            "scene",
            None,
            Some("t"),
            &root,
            false,
        )
        .expect("scaffold");

        assert_eq!(result.base_source, "fallback:default");
        let content = std::fs::read_to_string(&result.script_file).expect("read");
        assert!(content.contains("local base = vdsl.subject(\"1girl, solo, 20 years old\")"));
    }

    // -------------------------------------------------------------------------
    // T8: shot name with '/' returns InvalidShotName
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_invalid_shot_name() {
        let td = setup();
        let root = td.path().to_path_buf();

        let shots = vec![CamShotSpec {
            name: "bad/name".to_string(),
            seed: 1,
            trait_dsl: String::new(),
        }];
        let err = scaffold_cam_lua("persona_a", "scene", Some(&shots), Some("t"), &root, false)
            .expect_err("invalid shot name");

        assert!(
            matches!(err, CamLuaScaffoldError::InvalidShotName(_)),
            "expected InvalidShotName, got {err:?}"
        );
    }

    // -------------------------------------------------------------------------
    // T9: auto-mkdir creates missing root directory
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_auto_mkdir() {
        let td = setup();
        let root = td.path().join("nested").join("dir").join("projects");

        assert!(!root.exists(), "pre: nested dir should not exist");

        let result = scaffold_cam_lua("persona_a", "scene", None, Some("mkdir_test"), &root, false)
            .expect("scaffold");

        assert!(root.exists(), "root should be created by scaffold");
        assert!(result.script_file.exists());
        assert!(result.file_created);
    }

    // -------------------------------------------------------------------------
    // T10: template has no unfilled __CAM_* placeholders after expansion
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_no_unfilled_placeholders() {
        let td = setup();
        let root = td.path().to_path_buf();

        let shots = vec![CamShotSpec {
            name: "shot1".to_string(),
            seed: 99,
            trait_dsl: String::new(),
        }];
        let result = scaffold_cam_lua(
            "alice",
            "outdoor scene",
            Some(&shots),
            Some("outdoor"),
            &root,
            false,
        )
        .expect("scaffold");

        let content = std::fs::read_to_string(&result.script_file).expect("read");
        assert!(
            !content.contains("__CAM_"),
            "found unfilled placeholder in output:\n{content}"
        );
    }

    // -------------------------------------------------------------------------
    // T11: trait_dsl is emitted as a Lua expression verbatim (no string wrap)
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_trait_dsl_pass_through() {
        let td = setup();
        let root = td.path().to_path_buf();

        let shots = vec![CamShotSpec {
            name: "shot1".to_string(),
            seed: 1,
            // Catalog reference + composition: emitted verbatim as Lua expr
            trait_dsl: "C.play.pose_op_m + C.figure.clothing.t_shirt".to_string(),
        }];
        let result = scaffold_cam_lua(
            "persona_a",
            "scene",
            Some(&shots),
            Some("pass_through"),
            &root,
            false,
        )
        .expect("scaffold");

        let content = std::fs::read_to_string(&result.script_file).expect("read");
        // Verbatim Lua expression must appear (not wrapped in vdsl.trait("..."))
        assert!(content.contains("trait = C.play.pose_op_m + C.figure.clothing.t_shirt"));
        assert!(!content.contains(r#"vdsl.trait("C.play.pose_op_m"#));
    }

    // -------------------------------------------------------------------------
    // T12: legacy snap-* base alias appended when identifier differs from `base`
    // -------------------------------------------------------------------------
    #[test]
    fn test_scaffold_cam_lua_legacy_snap_alias() {
        // Create a fake legacy snap base file so stage-2 fallback fires
        let td = setup();
        let home_dir = td.path().join("home");
        let snap_dir = home_dir
            .join(".claude")
            .join("skills")
            .join("snap-testpersona");
        std::fs::create_dir_all(&snap_dir).expect("create snap dir");
        let base_file = snap_dir.join("testpersona_base.lua");
        std::fs::write(
            &base_file,
            r#"local testpersona_base = vdsl.subject("test subject")
  :quality("high")
"#,
        )
        .expect("write base");

        // resolve_base_snippet is not directly testable without HOME override,
        // so we test the alias-appending logic inline instead.
        let persona_id = "testpersona";
        let snippet = std::fs::read_to_string(&base_file).expect("read base");
        let alias_id = format!("{persona_id}_base");
        let aliased = if snippet.contains(&format!("local {alias_id}")) {
            format!("{snippet}\nlocal base = {alias_id}")
        } else {
            snippet.clone()
        };
        assert!(
            aliased.contains("local base = testpersona_base"),
            "alias line must be appended:\n{aliased}"
        );
    }
}
